### ISSUE TITLE
Database for user microservice

### ISSUE THREAD

**Issue by swomfire** [Adaption/basis#8]
- [x] Structure script
- [x] Data example
- [x] Document

**Comment by anh-khue** [comment]
@swomfire please remember to move this issue on Kanban Board for monitoring purpose. And tag me to inform once any issue is finished.

**Comment by anh-khue** [comment]
@swomfire What exactly does the field `value` in table `role_has_permission` do? What is the difference between values? And what does that value have to do the permission?
Please fix your document to be clearer.

**Comment by swomfire** [comment]
add new commit to the branch. Commit code c06cf549af58284e7170d04ad3bd6abad39c8529

**Comment by anh-khue** [comment]
@swomfire Next time, please reference the issue in commit message. And there are some problems.
1. Why there is a table called `payment` with description "Describe all payment in the system"?
- Writing that description means you've already understand that table should be used for managing transactions all around the system, so why did you put it in USER SERVICE?
- That `payment` table belongs to PAYMENT SERVICE, which I have no attempt to work on yet, because it relates to lot of things with 3rd-party APIs.
2. YOUR PROBLEM
- **Please be concentrate on your work, and DO NOT copy EVERYTHING from the old document without thinking. If I mean to do that, I'd not have asked for your help, because I know you can do much better than this.**
- **Use what you've learned and follow OUR use cases. Re-create the service as you think it should be and discuss with me.**
- **We are RE-DESIGN a system, not upgrading it. Please, put more effort on your work.**
